### ISSUE TITLE
serialized_attributes is deprecated in Rails 5.0

### ISSUE THREAD

**Issue by josephpage** [ForestAdmin/forest-rails#100]
La gem `forest-liana` provoque un grand nombre d'alertes (avec Rails 4.2.7 en tout cas) :
`DEPRECATION WARNING: `serialized_attributes` is deprecated without replacement, and will be removed in Rails 5.0.`

par exemple lors du lancement d'une console `rails console`

**Comment by arnaudbesnier** [comment]
Hi @josephpage, thanks for the report. I will make a Pull Request to clean this.

**Comment by arnaudbesnier** [comment]
@josephpage The fix is done, the new package version will be released soon!

**Comment by josephpage** [comment]
So the #100th issue will be resolved.
Congrats ! ;)

**Comment by arnaudbesnier** [comment]
The new version (1.5.8) of the gem has been published
