### ISSUE TITLE
Pie Charts - Issue when creating a chart from a belongs_to relationship

### ISSUE THREAD

**Issue by eddiedsitt** [ForestAdmin/forest-rails#110]
I have two classes

`class Casino < ApplicationRecord
  has_many :coupons
end`
and
`class Coupon < ApplicationRecord
  belongs_to :casino
end`

when i try to create a chart in forest grouping coupons by any of the casino's properties, i get an exclamation point and "Forest cannot render this chart". 

when i look at my console, i see the following error:
`NoMethodError - undefined method `split' for nil:NilClass:
  forest_liana (1.5.11) app/services/forest_liana/operator_value_parser.rb:58:in `get_field_name'
  forest_liana (1.5.11) app/services/forest_liana/operator_value_parser.rb:35:in `get_condition'
  forest_liana (1.5.11) app/services/forest_liana/value_stat_getter.rb:17:in `block in perform'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `each'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `public_send'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `try!'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:6:in `try'
  forest_liana (1.5.11) app/services/forest_liana/value_stat_getter.rb:15:in `perform'
  forest_liana (1.5.11) app/controllers/forest_liana/stats_controller.rb:19:in `show'`

any idea what it could be?

**Comment by arnaudbesnier** [comment]
hi @eddiedsitt thanks for the feedback, we'll try to reproduce your issue and let you know as soon as it will be fixed

**Comment by arnaudbesnier** [comment]
hey @eddiedsitt this feature is supposed to work properly, we tried to reproduce it without success.
Can you provide us a copy of the request log to help us ; something like this:

```
Started POST "/forest/stats/comments" for 127.0.0.1 at 2017-03-23 18:19:12 +0100
Processing by ForestLiana::StatsController#show as HTML
  Parameters: {"type"=>"Value", "collection"=>"comments", "timezone"=>"+01:00", "aggregate"=>"Count", "time_range"=>nil, "filterType"=>"and", "filters"=>[{"field"=>"customer:lastname", "value"=>"$present"}], "stat"=>{"type"=>"Value", "collection"=>"comments", "timezone"=>"+01:00", "aggregate"=>"Count", "time_range"=>nil, "filterType"=>"and", "filters"=>[{"field"=>"customer:lastname", "value"=>"$present"}]}}
```

**Comment by eddiedsitt** [comment]
here you go (not the same models but same error):

`Started POST "/forest/stats/orders" for ::1 at 2017-03-24 12:26:25 -0400
Processing by ForestLiana::StatsController#show as HTML
  Parameters: {"type"=>"Pie", "collection"=>"orders", "timezone"=>"-04:00", "group_by_field"=>"order_status:name", "aggregate"=>"Count", "time_range"=>nil, "filters"=>[], "stat"=>{"type"=>"Pie", "collection"=>"orders", "timezone"=>"-04:00", "group_by_field"=>"order_status:name", "aggregate"=>"Count", "time_range"=>nil, "filters"=>[]}}
   (3.0ms)  SELECT DISTINCT COUNT(DISTINCT "orders"."id") AS count_id, order_statuses.name AS order_statuses_name FROM "orders" LEFT OUTER JOIN "order_statuses" ON "order_statuses"."id" = "orders"."order_status_id" GROUP BY order_statuses.name ORDER BY count_id DESC
Completed 500 Internal Server Error in 9ms (ActiveRecord: 3.0ms)



NoMethodError - undefined method `type' for nil:NilClass:
  forest_liana (1.5.11) app/services/forest_liana/pie_stat_getter.rb:34:in `block in perform'
  forest_liana (1.5.11) app/services/forest_liana/pie_stat_getter.rb:29:in `each'
  forest_liana (1.5.11) app/services/forest_liana/pie_stat_getter.rb:29:in `map'
  forest_liana (1.5.11) app/services/forest_liana/pie_stat_getter.rb:29:in `perform'
  forest_liana (1.5.11) app/controllers/forest_liana/stats_controller.rb:19:in `show'
  actionpack (5.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  actionpack (5.0.1) lib/abstract_controller/base.rb:188:in `process_action'
  actionpack (5.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'`

**Comment by eddiedsitt** [comment]
@arnaudbesnier I'm still seeing the issue.. i cant create pie charts grouped by the belongs_to class (OrderStatus)and i cant create single value charts filtered by the belongs_to class (OrderStatus)

**Comment by arnaudbesnier** [comment]
hey @eddiedsitt , is it still the same stack trace? I didn't know that you also had an issue with the Value Charts. Are you consuming a MySQL database?

**Comment by eddiedsitt** [comment]
hey @arnaudbesnier , using Postgres and yes, also seeing it as an issue in another place, where i am trying to group coupons by casino(belongs_to)

```
Started POST "/forest/stats/coupons" for ::1 at 2017-03-29 14:23:59 -0400
  Parameters: {"type"=>"Value", "collection"=>"coupons", "timezone"=>"-04:00", "aggregate"=>"Sum", "time_range"=>nil, "filters"=>[], "stat"=>{"type"=>"Value", "collection"=>"coupons", "timezone"=>"-04:00", "aggregate"=>"Sum", "time_range"=>nil, "filters"=>[]}}

NoMethodError - undefined method `type' for nil:NilClass:
  forest_liana (1.5.11) app/services/forest_liana/operator_value_parser.rb:70:in `format_value'
  forest_liana (1.5.11) app/services/forest_liana/operator_value_parser.rb:52:in `get_condition'
  forest_liana (1.5.11) app/services/forest_liana/value_stat_getter.rb:17:in `block in perform'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `each'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `public_send'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:17:in `try!'
  activesupport (5.0.1) lib/active_support/core_ext/object/try.rb:6:in `try'
```

**Comment by arnaudbesnier** [comment]
@eddiedsitt are you still using Forest liana 1.5.11? You should update the liana to the latest version to get the fixes (1.5.18).

Let me know if the issue persist with the latest version.

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
@eddiedsitt also an issue may still persist for value charts; the one you described in your latest comment. I'll investigate this tomorrow.

**Comment by eddiedsitt** [comment]
@arnaudbesnier updating to the latest version of forest liana (1.5.23) and it worked!
