### ISSUE TITLE
Custom Integrations / Auth / CSS or Design 

### ISSUE THREAD

**Issue by bluengreen** [ForestAdmin/forest-rails#114]
How would I go about creating a custom integration? 

How would I go about securing my admin interface with my legacy authentication store or oauth provider? 

How would I customize the design (CSS/SCSS)? 

Thanks

**Comment by arnaudbesnier** [comment]
Hi @bluengreen 

If you need to create a custom integration the best way to do it is to contribute and implement your integration in the Rails liana code. As example you can look into our current integrations code (Intercom, Stripe,...).

About the security of your admin interface, the best and simplest way to handle it is to use the built-in Forest user authentication. If you have existing admin users for you current admin interface, invite them in Forest ;)

About the design, it is not currently possible to customise the style of the UI. 
By the way, we will release a brand new design at the end of the week.
Hope you'll like it!

**Comment by bluengreen** [comment]
Ok. Thanks. So if our systems are built on API's / service oriented architecture, would you say the best way to use forest is to create an integration?

**Comment by arnaudbesnier** [comment]
I am not really sure to understand. Do you have a micro service architecture or do you have a single Rails app consuming a single database?

**Comment by bluengreen** [comment]
We don't have micro services but have several services for various things, processing payments, customer search, notifications, etc. These are our own internal services, not meant to be opensourced.

**Comment by arnaudbesnier** [comment]
So if you have a single database, it should work properly.
Did you try to install Forest on your Rails then?

**Comment by bluengreen** [comment]
Yes. But the services data isn't in the local database. So no resources were built on load.

**Comment by arnaudbesnier** [comment]
So you need to implement what we call Smart Collections. Here is an example: http://doc.forestadmin.com/developers-guide/#creating-a-smart-collection

**Comment by bluengreen** [comment]
hmmm That's interesting. Following the example from the link, can Item be say an active resource or a Her model? All Forest cares about is that the route returns json right? 

Thanks
