### ISSUE TITLE
Pagination and search for SmartCollections

### ISSUE THREAD

**Issue by jdbwin** [ForestAdmin/forest-rails#115]
Hi there, thanks for this great app!

I just setup a few `SmartCollections` and I am aiming to have them function similar to the 'default' collections.

Is there any documentation for paginating these `SmartCollections` and making them searchable?

Thanks!

**Comment by jdbwin** [comment]
Nm, figured it out :)

**Comment by jdbwin** [comment]
Hey,

I have pagination working fine with `SmartCollections`, however, I can't figure out how to get search working.

Right now, when I check the view for my `SmartCollection`, the search bar is disabled client side.

What is expected to be passed so that a `SmartCollection` is searchable?

Thanks!!

**Comment by arnaudbesnier** [comment]
If you want to implement the search, you need to implement it in the `controller` `index` action. Here is the documentation for Smart Collections : http://doc.forestadmin.com/developers-guide/#creating-a-smart-collection

About the disabled search bar you noticed, it might be a design regression of our new interface.

**Comment by jdbwin** [comment]
Hey @arnaudbesnier ,

Thanks for this!

I followed the docs here when creating a Smart Collection. The search bar is still disabled when implementing the search in the controller.

**Comment by arnaudbesnier** [comment]
Hi @jdbwin sorry for the late response, I have added an issue about that. One of our developer will investigate this issue in next week sprint.

Thanks for your patience!

**Comment by arnaudbesnier** [comment]
Hey @jdbwin, good news, the search bar will be back soon. This [PR](https://github.com/ForestAdmin/forest-rails/issues/115) will let developers set the `is_searchable` property to `true` (default value is `false`) to display the search bar for Smart Collections (when, as a developer, you implemented the Smart Collection search). 

This fix will be released in the next release!

**Comment by jdbwin** [comment]
@arnaudbesnier ,

That's great to hear!

Thanks for the update on the situation and the work!

**Comment by arnaudbesnier** [comment]
@jdbwin, this is now released.
You have to do 2 things to make it work:

- Upgrade to the latest liana version,
- define `is_searchable: true` for the Smart Collections having the search implemented.

🌲🌲🌲
