### ISSUE TITLE
Forest and Single Table Inheritance

### ISSUE THREAD

**Issue by josephpage** [ForestAdmin/forest-rails#123]
Forest doesn't recognize STI.
I would love to be able to have : 
  - different layout configuration for sub-classes
  - automatic and magic creation of segments for each sub-class

**Comment by arnaudbesnier** [comment]
Hey @josephpage , the Rails liana has a minimal support for STI models, see the changelog: https://github.com/ForestAdmin/forest-rails/blob/devel/CHANGELOG.md#release-1348---2016-10-28.

**Comment by SeyZ** [comment]
Hey @josephpage - good news, we've improved our support of STIs: https://github.com/ForestAdmin/forest-rails/pull/128

Feel free to reopen this issue if you have any question / issue :)

**Comment by SeyZ** [comment]
Let me reopen this issue. I think it's a very good idea to automatically create segments for each sti children. 

Currently, we automatically set the `type` or the `inheritance_column` as an enum on the STI parent model. You can manually add segments, it's very easy. For example. `type is lion`, `type is wolf`, etc.

We've also on our roadmap the feature to customize the fields visibility of segments independently. Today, the configuration is shared between the collection and the segments. I think it is another issue but i'll keep you posted when we work on it 👍 

Thoughts?

**Comment by arnaudbesnier** [comment]
This feature is now release in the new liana version 2.0.0.
Hope you'll have the opportunity to enjoy it @josephpage !

🌲🌲🌲

**Comment by josephpage** [comment]
Neat ! I will explore this new release
