### ISSUE TITLE
certificate verify failed (OpenSSL::SSL::SSLError) 

### ISSUE THREAD

**Issue by ergxpr0xy** [ForestAdmin/forest-rails#131]
i got this error when do `rails s` 
```
/Ruby2.2.0/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
```
installation was smooth
how to fix this?

**Comment by arnaudbesnier** [comment]
Hi @ergxpr0xy, which version of Rails and Forest liana gem are you using?

**Comment by arnaudbesnier** [comment]
@ergxpr0xy we just made some changes on our SSL certificates, we hope it will fix your issue. Can you try to install your project again?

**Comment by SeyZ** [comment]
Hello @ergxpr0xy ,

Thank you for your issue. You're completely right, our SSL configuration had an problem. The "Intermediate Certificate" (chain certifs) was not all correctly installed, meaning there're no issue on most browsers/tools but "sometimes" the certificate is not considered as trustable.

We've fixed this SSL issue. Can you try again now? Please, let me know if it works or not ;) Feel free to reopen this issue if necessary of course :)
