### ISSUE TITLE
JSONAPI::Serializer monkey patch broken

### ISSUE THREAD

**Issue by nemile** [ForestAdmin/forest-rails#15]
Hi,

Last jsonapi-serializers release is breaking the gem.
Here's my Gemfile:
```
gem 'forest_liana', '~> 1.3', '>= 1.3.14'
```
Here's the error I get when I try to start my rails server:
```
/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/forest_liana-1.3.14/lib/forest_liana/bootstraper.rb:39:in `find_serializer_class_name': wrong number of arguments (2 for 1) (ArgumentError)
```
This is caused by this PR https://github.com/fotinakis/jsonapi-serializers/pull/79

**Comment by SeyZ** [comment]
Thanks for report! You're right
