### ISSUE TITLE
$blank and $present filters broken

### ISSUE THREAD

**Issue by nemile** [ForestAdmin/forest-rails#16]
Parsed value is set to nil [here](https://github.com/ForestAdmin/forest-rails/blob/devel/app/services/forest_liana/operator_value_parser.rb#L19-L25).

And then [here](https://github.com/ForestAdmin/forest-rails/blob/devel/app/services/forest_liana/operator_date_interval_parser.rb#L19) raises:
> undefined method `to_sym' for nil:NilClass

forest_liana (1.3.15) app/services/forest_liana/operator_date_interval_parser.rb, line 19
-----------------------------------------------------------------------------------------

``` ruby
   14       def initialize(value)
   15         @value = value
   16       end
   17   
   18       def is_interval_date_value
>  19         return true if PERIODS[@value.to_sym]
   20   
   21         match = PERIODS_LAST_X_DAYS.match(@value)
   22         return true if match && match[1]
   23   
   24         false
```

**Comment by SeyZ** [comment]
Thanks for report!
