### ISSUE TITLE
[QUESTION] Implementation of a SmartCollections with a Ruby application

### ISSUE THREAD

**Issue by virtualflo** [ForestAdmin/forest-rails#162]
Hello guys, 

I spent the night trying to create a basique "smart collections" for my application. 
I explore the git of Forest-Rails-Demo with the Brands example.
But after hours of work i still have an error message "Cannot reach your data" when i'm trying to access the smart collections. 

Here my code: 

stage.rb

```
class Forest::Stage
  include ForestLiana::Collection

  collection :stages
  field :stage, type: 'String'
  field :count, type: 'Number'
end
```

stages_controller.rb

```
# ForestLiana::ApplicationController takes care of the authentication for you.
class Forest::StagesController < ForestLiana::ApplicationController
  def index
    records = Request.all

    if params[:search]
      records = records.where("brand ILIKE '%#{params[:search]}%'")
    end

    if params[:filter] && params[:filter][:stage]
      records = records.where(stage: params[:filter][:stage])
    end

    result = records
      .group(:language_request)
      .order(:language_request)
      .count
      .map.with_index do |f, index|
        {
          id: index,
          type: 'stages',
          attributes: {
            stage: f.first,
            count: f.second
          }
        }
      end
    render json: { data: result }
  end
end
```

config/routes

```
Rails.application.routes.draw do

  #forest set-up
  namespace :forest do
    resources :stages
  end
...
```

I have this kind of output

```
{"data":
  [
    { "id":0,
      "type":"stages",
      "attributes":
        {
          "stage":"",
          "count":5
        }
    },

    {"id":1,
      "type":"stages",
      "attributes":
        {
          "stage":"EN",
          "count":16
        }
    },

    {"id":2,
      "type":"stages",
      "attributes":
          {
            "stage":"FR",
            "count":22
          }
    },

    {"id":3,
      "type":"stages",
      "attributes":
          {
            "stage":"IT",
            "count":1
          }
    }
  ]
}
```

Can you tell me why the ForestAdmin cannot reach my data ?
Forest recognize the columns stage and count.
The others tables are available. 

Thank you,

**Comment by arnaudbesnier** [comment]
Hi @virtualflo, like you said, your Smart Collection schema is properly detected by Forest.
If the output you mentioned is the payload the browser receive, we might have an issue in the interface "adapter".

Can you show a screenshot of the network tab in your browser console? I'd like to check that the payload in the request response is correct.

You might have an error in the console too. Another screenshot would be interesting for this error trace.

Thanks

**Comment by virtualflo** [comment]
Hi @arnaudbesnier, here the screenshots you asked ;-) 

Network tab
![capture d ecran 2017-07-06 a 09 37 15](https://user-images.githubusercontent.com/4353596/27900485-d9a7f50a-622e-11e7-8e52-6f55b9465eb4.png)

Console
![image](https://user-images.githubusercontent.com/4353596/27900520-f9624292-622e-11e7-88fa-00a37cedd393.png)

**Comment by arnaudbesnier** [comment]
Thanks @virtualflo, I feel that something is missing in the doc, you might need to set a
`meta: { count: 4 }`. So you don't have any errors in your browser console (console tab)?

**Comment by virtualflo** [comment]
I have an error in my browser console. 
![image](https://user-images.githubusercontent.com/4353596/27920806-11335004-6276-11e7-9854-19aafd9a0adb.png)

**Comment by virtualflo** [comment]
Hi @arnaudbesnier , if you have some ideas i can test it :-)

**Comment by arnaudbesnier** [comment]
@virtualflo did you setup the CORS middleware?

<img width="890" alt="screen shot 2017-07-07 at 18 06 52" src="https://user-images.githubusercontent.com/664261/27966323-22e625d2-633f-11e7-84d7-eb251b462203.png">

**Comment by virtualflo** [comment]
No i didn’t. I just did and it’s working :-) You should add this information in the documentation and not only the ‘value chart’ part ;-)
Thank you very much.

**Comment by arnaudbesnier** [comment]
Sorry for that, we will definitely fix the documentation about this missing step.
Hope you'll fully enjoy Forest now :)

🌲🌲🌲
