### ISSUE TITLE
[QUESTION] Multiple images uploading

### ISSUE THREAD

**Issue by glevha** [ForestAdmin/forest-rails#163]
Hello,

Thanks for your amazing product!
I have a question though. We are using carrierwave to upload multiple images on our Product model (using a string field :images as an array). However, I can't manage to do multiple images upload directly in Forest: my field as array doesn't allow me to generate multiple filepickers (I just have a text field). It is only working for single image.

I also tried using attachinary gem, but it was even worth. Do you have any idea how to manage this (displaying multiple filepickers)? Or should I go for an Image model handled by carrierwave and belonging to Product?

Thank you for your support!

**Comment by arnaudbesnier** [comment]
Hi @glevha, Multiple images uploading is not something we support right now. But that's definitely something we have in mind (ie a "carousel" widget).

If you really want to use Forest for this kind of operation, yes, changing your database schema could be a solution to make single images upload with Forest.

**Comment by glevha** [comment]
Hi @arnaudbesnier and sorry for the time! We updated our DB schema in order to achieve that. Forest is really powerful! 

Thanks!
