### ISSUE TITLE
[DEPRECATION] uniq deprecated

### ISSUE THREAD

**Issue by bartdejonge1996** [ForestAdmin/forest-rails#165]
I'm getting this deprecation warning from the stats controller, can this be looked into?

DEPRECATION WARNING: uniq is deprecated and will be removed from Rails 5.1 (use distinct instead) (called from count at [ruby_path]/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/forest_liana-1.6.13/app/services/forest_liana/value_stat_getter.rb:59)

**Comment by arnaudbesnier** [comment]
Hi @bartdejonge1996, thank you for the report.
We will have a look at this issue this week.
