### ISSUE TITLE
[QUESTION] Smart Collection specific style for Enum column + show redirection

### ISSUE THREAD

**Issue by virtualflo** [ForestAdmin/forest-rails#167]
Hello the Forest Team, 

I created a smart collection 'STAGE' to view the stage of all my orders.

It's working and it's great but i have two issues to finalize it:

1. I have two Enum type column and I would like the same style (it's the style of one of my table):

![image](https://user-images.githubusercontent.com/4353596/28019527-89943e6a-6581-11e7-9276-1ff568adefdc.png)

How ForestAdmin can detect an Enum column for a smart collection ? 

2 - For the moment when i click on a line of my Smart Collection i have a message error "This Stage does not exist."
When i click on a line i would like to be redirect to the Request associate. I know how to find the ID of the Request in the params but i don't know how to passed it to Forest to open te 'show' of the request concerned. 

Do you have a recommandation ? 

I'm just starting to configure my ForestAdmin but it's look awesome,

**Comment by arnaudbesnier** [comment]
Hey @virtualflo,

To create an enum column/field for your Smart Collection, you can declare your field this way:
```javascript
{ field: 'country', type: 'Enum', enums: ['USA', 'CA', 'NZ'] }
```

"This Stage does not exist." appears because you did not implement the `show` request for your "Stage" Smart Collection. The only solution I have in mind to give you a direct access to the associated "Request" is to add a `belongsTo` field like this:
```javascript
{ field: 'request', type: 'Number', reference: 'requests.id' }
```
and then, populate the field in the index response.

**Comment by virtualflo** [comment]
Thanks @arnaudbesnier. Now my enum is correctly recognize with ForestAdmin. 

About the second problem i tried to implement the show method because i didn't succeed to implement your solution.

```
# in stages_controller
...
def show
  request = Request.find(params.dig('id'))
end
...
```
This method return the correct instance of request

The route are correct because the method is execute when i click on a line of my collection.
But ForestAdmin still have the same error message :-/

**Comment by virtualflo** [comment]
@arnaudbesnier, how can i create a link between an id column and the show of the instance in question. For exemple Forest autogenerate the link with my main tables.
If i can do this, it's enough.

![image](https://user-images.githubusercontent.com/4353596/28141952-1dff1898-675f-11e7-992b-2c95764cd0c4.png)

**Comment by arnaudbesnier** [comment]
@virtualflo, if you want to have this kind of display, you have to declare your field this way:
```ruby
field :video, type: 'Number', reference: 'videos.id'
```

And then send the videos associated to the records (and well formated) in the index responses.

**Comment by arnaudbesnier** [comment]
Everything is in the documentation: https://doc.forestadmin.com/developer-guide/rails.html.

As I didn't get any news, I guess everything is going fine for you now.
