### ISSUE TITLE
Smart fields, has_many relation trying a reverse belongs_to

### ISSUE THREAD

**Issue by daniel-costa** [ForestAdmin/forest-rails#171]
I'm trying to create a Smart Field in order to count the relations from a model. I basically have this associations:

#### Venue
```ruby
class Venue < ApplicationRecord
  belongs_to :region, optional: true
  has_many :food_types
end
```
#### Region
```ruby
class Region < ApplicationRecord
  has_many :venues
end
```
#### FoodType
```ruby
class FoodType < ApplicationRecord
  has_many :venues
end
```

#### Region
```ruby
class Forest::Region
  include ForestLiana::Collection
  collection :regions
  field :number_of_venues, type: 'Number' do
    object.venues.count
  end
end
```
#### FoodType
```ruby
class Forest::FoodType
  include ForestLiana::Collection
  collection :food_types
  field :number_of_venues, type: 'Number' do
    object.venues.count
  end
end
```

### Error
```console
Completed 500 Internal Server Error in 66ms (ActiveRecord: 13.0ms)
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column venues.food_type_id does not exist
LINE 1: SELECT COUNT(*) FROM "venues" WHERE "venues"."food_type_id" ...
                                            ^
: SELECT COUNT(*) FROM "venues" WHERE "venues"."food_type_id" = $1):
  
lib/forest_liana/collections/food_type.rb:7:in `block in <class:FoodType>'
```

I can't figure out how to make it work and it seems forest is thinking I'm using a `belongs_to` in the "other side" of the relation.

**Comment by arnaudbesnier** [comment]
Hi @daniel-costa, I don't think this is related to Forest.

Are you sure your database tables and your Active Record models are properly configured?
It seams that `Venue` and `FoodType` should have a `has_and_belongs_to_many` relationship, am I wrong?

In any ways, the errors that happen in the Smart Field computation block (ie your business logic code) are most of the time errors coming from developers code.

Let me know if I am wrong.

**Comment by daniel-costa** [comment]
You are not wrong. Sorry for that.
