### ISSUE TITLE
UX tiny detail slowing down configuration

### ISSUE THREAD

**Issue by daniel-costa** [ForestAdmin/forest-rails#172]
Hi,

I'm using your product for a new project and going through the configuration of 4 models, I've something that really bugs me just a tiny bit but is making me insane.

When you have a fresh model to configure the fields, every time you save you get that message:
<img width="404" alt="screen shot 2017-08-03 at 2 49 06 pm" src="https://user-images.githubusercontent.com/10674268/28924994-758a7672-785b-11e7-83da-a84e269a94be.png">

No big deal with the message, but the placement is a pain as it is on top of the save button. It stays longer than the time it takes me to do:
- click field
- pick type
- save
- click next field
- pick type

If it was moved a bit higher than there (just on top of the save button for example) it will be wonderful.

I know it's tiny and not that big of a deal, but is still irritating. Thought you might know that.

---

BTW: I just saw you moved the "text field" option above the "text area" option: **good move guys**

---
In a mother note, I love your product. It's 5 years I deal with startups with products changing web habits and reinvent ways of doing stuff. And I have to say that Forest is **the** tool that is needed.

Mark my words, in 5 years you gonna be acquired by one of the big tech names. mark my words...

**Comment by daniel-costa** [comment]
Any news about this issue?

**Comment by arnaudbesnier** [comment]
Hey @daniel-costa, we took the time to make the experience better on this point.
We will release something on Monday/Tuesday for sure.

**Comment by arnaudbesnier** [comment]
Hi @daniel-costa, the improvement has been released this morning.
Hope you'll enjoy it.

Thanks for the valuable feedback.

🌲🌲🌲
