### ISSUE TITLE
[1.6.17] Customization of attributes presence validation

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#180]
On object creation, attributes having presence validation can't be submitted (marked as "can't be blank"). How can we customize this validation to disable it on specific attributes?

In my case, I have many default values defined in `before_validation` filters so I would like the form to actually accept blank values for certain attributes.

Thanks!

**Comment by arnaudbesnier** [comment]
Thanks for the report, we have to think about a better validations integration.

**Comment by arnaudbesnier** [comment]
Hi @lucasgerard, I think the first thing we will do is to remove all validations in the models where a `before_validation` is defined. This should be done before the end of the week.

**Comment by arnaudbesnier** [comment]
@lucasgerard, this is fixed in the latest liana version (1.7.2).
Let me know if your issues persist.

🌲🌲🌲
