### ISSUE TITLE
[1.6.17] Creating child objects from the "Related Data" section of a details view

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#181]
Classic relationship `Event has_many :deals` :
as I create a new `deal` from an `event` details view (in the "Related Data" section), the relationship is not included, hence the deal does not belong to the event.

Looking at the json, "event" data is nil indeed.
![screen shot 2017-08-17 at 17 18 30](https://user-images.githubusercontent.com/5589858/29453904-9087cd74-840b-11e7-8441-c5d4782e15ce.png)

Thanks!

**Comment by arnaudbesnier** [comment]
Hi @lucasgerard, as mentioned on Slack, we will fix this, this week.

(You forgot to mention that the issue appear only if the foreign key field is hidden in the creation form.)

**Comment by arnaudbesnier** [comment]
@lucasgerard, the fix is currently under review it should be release today or tomorrow (no liana update is necessary)

🌲🌲🌲

**Comment by arnaudbesnier** [comment]
The fix is now released!
