### ISSUE TITLE
UI bug on child form in details view : actions outside screen

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#182]
Hey!

When object name is too long, action buttons in related datas are outside the screen. See screenshot attached.

![screen shot 2017-08-21 at 17 00 12](https://user-images.githubusercontent.com/5589858/29525232-3b5143e2-8692-11e7-993e-9256e5d3325f.png)

Thanks!

**Comment by arnaudbesnier** [comment]
Thanks for the report @lucasgerard, we will try to find a fix before the end of the week.

**Comment by arnaudbesnier** [comment]
@lucasgerard The fix has been deployed to production 🎉 
You just have to refresh the Forest UI and enjoy!

🌲🌲🌲
