### ISSUE TITLE
Wrong pasting in secrets.yml

### ISSUE THREAD

**Issue by fcatuhe** [ForestAdmin/forest-rails#188]
Hello, when running `rails g forest_liana:install _my_key_` in Rails 5.1, I get this in my secrets.yml:
```ruby
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>` environment over there.
```
in the test section, which breaks the comment.

**Comment by arnaudbesnier** [comment]
Hi @fcatuhe, thank you for the report.
We'll try to reproduce the issue and then fix it.

As a workaround, I guess that you can manually edit the `secrets.yml` file, right?

**Comment by fcatuhe** [comment]
Yes I worked it around, it was just for your bug record. Thanks

**Comment by arnaudbesnier** [comment]
Hi @fcatuhe,
The fix is now released in the new liana version 1.7.10.

🌲🌲🌲

**Comment by daniel-costa** [comment]
Deploy this gem on a new project with the latest version and still happens.

**Comment by arnaudbesnier** [comment]
hey @daniel-costa can you specify which version of Rails you're using?

**Comment by arnaudbesnier** [comment]
@daniel-costa, just tried on a new Rails 5.1 project, and it works perfectly.
