### ISSUE TITLE
forest_liana gem 2.0.0 update not working

### ISSUE THREAD

**Issue by rodoneill** [ForestAdmin/forest-rails#210]
Ran bundle update on an existing project, which updated forest_liana gem from 1.9.8 to 2.0.0, installed successfully. Tried to boot the app locally and failed with the following boot error:

`C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/app/serializers/forest_liana/serializer_factory.rb:15:in `const_set': wrong constant name ActiveRecord::SessionStoreSessionSerializer (NameError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/app/serializers/forest_liana/serializer_factory.rb:15:in `define_serializer'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/app/serializers/forest_liana/serializer_factory.rb:252:in `serializer_for'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/lib/forest_liana/bootstraper.rb:75:in `block in create_factories'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/lib/forest_liana/bootstraper.rb:74:in `map'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/lib/forest_liana/bootstraper.rb:74:in `create_factories'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/lib/forest_liana/bootstraper.rb:24:in `perform'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/forest_liana-2.0.0/lib/forest_liana/engine.rb:51:in `block in <class:Engine>'
`

I've rolled back by specifying `gem 'forest_liana', '1.9.8'` in Gemfile which works fine. Deploying to Heroku also fails with the same 'wrong constant name' error in the build logs.

Ruby 2.2.6p396
Rails 5.1.4
Postgresql
Puma 3.0
Windows 10 local/Heroku prod

**Comment by arnaudbesnier** [comment]
@rodoneill thanks for the feedback, I'll try to investigate this week.

**Comment by arnaudbesnier** [comment]
Hey @rodoneill,

We released an new liana version (2.0.3) that should fix the regression you had.
Let me know if you still have some issues with this new version.

Thanks!

🎄🎄🎄

**Comment by rodoneill** [comment]
2.0.3 is a winner! Thanks @arnaudbesnier :+1:
