### ISSUE TITLE
[+] Smart Actions - Users want to pre-fill the form with the selected record values.

### ISSUE THREAD

**Issue by daniel-gato** [ForestAdmin/forest-rails#212]
I'm trying to figure out from your documentation how I could use a field value in Smart Action field?

I tried 
```
  action 'get gapi data', fields: [{
    field: 'query',
    type: 'String',
    isRequired: true,
    defaultValue: "#{object.name}",
    widget: 'text input'
  }]
```

I don't have that much hope that it is possible (due to the fact you can call a smart action on multiple records). But we never know.

**Comment by arnaudbesnier** [comment]
Hi @daniel-costa, you can't do that right now. This is something we definitely have in mind for the future.

**Comment by daniel-costa** [comment]
Ok.

I start thinking about it and it made sens, but when you add to it the multi record selection it becomes tricky real fast.

**Comment by arnaudbesnier** [comment]
Bulk Actions and "Single Record" Actions are useful for separate use cases. As a consequence, I think they will be split into 2 different features in the future.

**Comment by matthv** [comment]
I’m closing this inactive issue.
Don’t hesitate to open a new one if you encounter a bug.
