### ISSUE TITLE
Access only by segment Collection but

### ISSUE THREAD

**Issue by daniel-costa** [ForestAdmin/forest-rails#217]
Hi,

Bug encountered with collections and segments display for collection where we specify **access only by segments**

This isn't important but you should be aware of it.

## Expected behaviour

Lets take the example of this collection/segments:

```
[x] Venues
|--[ ] status editing
|--[x] status live
|--[x] status offline
```

NB: `[x]` stands for **shows** in the UI and `[ ]` stands for **is hidden** in the UI

When the user clicks on `Venues` we should see `status live` segment.

## Actual behavior

When the user clicks on `Venues` we see `status editing` instead.

**Comment by arnaudbesnier** [comment]
@daniel-costa, the fix has been released.
You just need to refresh your browser page to enjoy.

🎄🎄🎄

**Comment by daniel-costa** [comment]
Just tried + emptied cache + reloaded multiple times and it still does it.

**Comment by arnaudbesnier** [comment]
I fixed the redirect on browser page, but I forgot your initial issue... It will be fixed in a few minutes.

**Comment by arnaudbesnier** [comment]
@daniel-costa, The new fix is live. Does it work as expected for you now?

**Comment by daniel-costa** [comment]
Yep works. 

Just out of curiosity, what was the first fix made? I don’t recall posting about the browser redirection...

**Comment by arnaudbesnier** [comment]
I spotted a related issue while requesting the collection page to test the redirect on the right segment. Nothing more.
