### ISSUE TITLE
Smart action response rails 5

### ISSUE THREAD

**Issue by daniel-costa** [ForestAdmin/forest-rails#218]
The code for `smart actions` in the doc has deprecated code for rails 5

```
# ForestLiana::ApplicationController takes care of the authentication for you.
class Forest::CustomersController < ForestLiana::ApplicationController
  def ban_user
    # Your business logic to send an email here.
    render nothing: true, status: 204
  end
end
```

As this  [post](https://stackoverflow.com/questions/34688726/the-nothing-option-is-deprecated-and-will-be-removed-in-rails-5-1) suggests, it should be 

```
# ForestLiana::ApplicationController takes care of the authentication for you.
class Forest::CustomersController < ForestLiana::ApplicationController
  def ban_user
    # Your business logic to send an email here.
    head :ok
  end
end
```

**Comment by arnaudbesnier** [comment]
The equivalent to `status: 204` is actually `head :no_content`.
I'll fix it right now.

**Comment by daniel-costa** [comment]
You are right. I forgot to edit my initial post.

**Comment by arnaudbesnier** [comment]
@daniel-costa, here is the fix: https://github.com/ForestAdmin/forest-doc/commit/a5560c798e3d54f7937f620faf5d8698d344b794

It should be live in a few minutes.
Thanks for the feedback.

By the way, the documentation is open source (https://github.com/ForestAdmin/forest-doc).
If you have any issues with the current version, feel free to contribute submitting Pull Requests. ✨
