### ISSUE TITLE
Order attributes fields everywhere.

### ISSUE THREAD

**Issue by daniel-costa** [ForestAdmin/forest-rails#226]
## Expected behavior

I spotted multiple places where the attributes aren't in alphabetical order. As for the dashboard widget creation: 

Globally, filter all `<select>` in the dashboard to a default ASC order should be a good practice.

## Actual behavior

<img width="234" alt="screen shot 2018-01-11 at 3 34 50 pm" src="https://user-images.githubusercontent.com/10674268/34828263-a24fa084-f6e5-11e7-9d0a-3ba4f27ca185.png">

**Comment by arnaudbesnier** [comment]
Can you precise where you haven't an alphabetical order?
The actual behaviour you describe (ie your screenshot) is actually in the alphabetical order, am I wrong?

**Comment by daniel-costa** [comment]
I got the wrong screen (this one was for our internal doc) and I can’t find where it was.

You can close, I’ll reopen once I’ve the location of it. 

But I’m pretty sure it was ordered with the fiels order of the sql table (in the order I migrated them if it makes more sense)

**Comment by daniel-costa** [comment]
I found it finally.
<img width="233" alt="screen shot 2018-01-22 at 10 09 11 pm" src="https://user-images.githubusercontent.com/10674268/35243806-d6c544e2-ffc6-11e7-9422-9bd0d76d36a8.png">

It happens when you edit a segment and you choose a relation field, in my case, `venue` > `status`

On top of that, the enum values aren't sorted neither.

**Comment by daniel-costa** [comment]
@arnaudbesnier could we reopen this one?

**Comment by arnaudbesnier** [comment]
@daniel-costa A new client version will fix this tomorrow morning.

Thanks for the feedback.
