### ISSUE TITLE
Crash on boot while Forest is on maintenance mode

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#228]
## Expected behavior

Rails app should boot

## Actual behavior

While Forest is on maintenance mode, the rails app cannot boot, and this lead to a complete downtime of our application.

## Failure Logs

This crash happened twice in the last 7 days:

Friday 12th January, 18:11 UTC
Wednesday 17th January, 13:03 UTC

![screen shot 2018-01-17 at 14 27 36](https://user-images.githubusercontent.com/5589858/35045542-7631409e-fb94-11e7-9f2d-e96614800335.png)
![screen shot 2018-01-17 at 14 14 20](https://user-images.githubusercontent.com/5589858/35045555-7e54a400-fb94-11e7-9727-ca8ad7181c15.png)

## Context

Package Version: forest_liana (2.0.4)
Rails Version: rails (4.2.10)
Database Version: PG Version 9.6.6

**Comment by arnaudbesnier** [comment]
Hi @lucasgerard,
This is fixed in the latest liana version (2.1.1).

Thanks for the valuable feedback!
🌲🌲🌲
