### ISSUE TITLE
[*] Collections - Error edit view Users  

### ISSUE THREAD

**Issue by FredPetris** [ForestAdmin/forest-rails#245]
## Expected behavior

Display view Users

## Actual behavior

Oops, something went wrong : only  on 2 databases, the other are ok.

## Failure Logs

<img width="630" alt="capture d ecran 2018-03-06 a 08 34 51" src="https://user-images.githubusercontent.com/14973724/37022221-96bd7c0c-2122-11e8-957e-552b85ec5fbe.png">
<img width="648" alt="capture d ecran 2018-03-06 a 09 35 17" src="https://user-images.githubusercontent.com/14973724/37022222-96d9cd1c-2122-11e8-814e-70827d3276d8.png">

## Context

TODO: Please provide any relevant information about your setup.

* Package Version: Forest-Liana 2.3.3
* Rails Version: Rails 5.0.0.rc2
* Database Dialect: PostgreSQL
* Database Version: postgres (PostgreSQL) 9.4.5

**Comment by arnaudbesnier** [comment]
Hey @FredPetris, could you try to upgrade to the latest gem version and let us know if it fixes your issue?

**Comment by arnaudbesnier** [comment]
By the way, I don't think that the error about the Intercom integration setup is related to your issue.

**Comment by FredPetris** [comment]
Poke @arnaudbesnier, i've updrage to the latest version and my issue is not fix : impossible to browse user table. 
<img width="812" alt="capture d ecran 2018-03-24 a 22 36 12" src="https://user-images.githubusercontent.com/14973724/37869214-022adbe8-2fb4-11e8-8ede-97e15b93a2f3.png">
"cause" is a table and user belongs_to :cause

**Comment by FredPetris** [comment]
poke @arnaudbesnier : Have you been able to explore the problem ? 
We still can not consult our 2 most important tables.

**Comment by arnaudbesnier** [comment]
Hi @FredPetris, we've released a new liana version (v2.5.4) last week that contains a fix that could solve your issue (regression on tables having self-references).

Can you upgrade to the latest version and let us know if it works?

Thank you for the feedback

🌲🌲🌲

**Comment by FredPetris** [comment]
That's fine ! The new liana version fix our issue ! Thank's @arnaudbesnier.
