### ISSUE TITLE
Collection Not Found

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#249]
## Expected behavior

Collection should be found

## Actual behavior

Collection not found. Worth to mention that the two missing collections are the same than in my previous issue https://github.com/ForestAdmin/forest-rails/issues/224, so it might be related.

## Failure Logs

![screen shot 2018-03-28 at 15 57 45](https://user-images.githubusercontent.com/5589858/38033789-1a685fba-32a1-11e8-98b7-257b0dc9a53d.png)

## Context

Package Version: forest_liana (2.4.9)
Rails Version: rails (4.2.10)
Database Version: PG Version 9.6.6

**Comment by arnaudbesnier** [comment]
hey @lucasgerard, do you have any error logs to share (in you rails server or in your browser console?

Thanks!

**Comment by lucasgerard** [comment]
sorry for the late reply. No server logs as it was not reached, and indeed there is an error before in client logs

![screen shot 2018-04-17 at 15 38 10](https://user-images.githubusercontent.com/5589858/38873204-8174b74e-4255-11e8-8e57-02b25580f500.png)

**Comment by lucasgerard** [comment]
if you want to have a look on our integration, the two "missing" tables are Tag and Tagging.

**Comment by arnaudbesnier** [comment]
Hi @lucasgerard,

I guess you are using the ActAsTaggable gem, am I wrong?
If so, is the `Events` collection "taggable"?
What is the "related data" you wanted to open here? Is it "tags"?

The more details you can bring the faster the issue will be solved?

**Comment by lucasgerard** [comment]
Hey @arnaudbesnier, we're not using ActAsTaggable. We have a `Tag` model, and a `Tagging` table that links an `Event` to a `Tag`.

"The related data" are the tags associated to an event, that I would like to display and edit. Below are the relationships - they are quite basic. Hope it is more clear now!

```
class Event < ActiveRecord::Base
    has_many :taggings, :dependent => :destroy
    has_many :tags, through: :taggings
    [...]
end
```

```
class Tagging < ActiveRecord::Base
    belongs_to :event
    belongs_to :artist # tags can be associated to different models: event, tag, blog_post... the relationship is working nowhere
    belongs_to :tag
    belongs_to :blog_post
end
```

```
class Tag < ActiveRecord::Base
    has_many :taggings
    has_many :events, through: :taggings
    has_many :artists, through: :taggings
    has_many :blog_posts, through: :taggings

    scope :music, -> { where(typo: "music") }
    scope :spot, -> { where(typo: "spot") }
end
```

**Comment by arnaudbesnier** [comment]
@lucasgerard Something weird is that Forest shows `Tag` and `Tagging` collections on our side on your production environment, so they should be accessible from your left panel.

**Comment by lucasgerard** [comment]
@arnaudbesnier yes, they are not visible in my left global panel, as shown in the screenshots.

However, Tag and Tagging collections are visible in the Event object relations, but crash as I click on it (404 Error shown in previous comment)
![screen shot 2018-04-26 at 15 38 18](https://user-images.githubusercontent.com/5589858/39309338-0a484a18-4968-11e8-95b2-8b40438cc717.png)

![screen shot 2018-04-26 at 15 36 24](https://user-images.githubusercontent.com/5589858/39309194-b3a77f26-4967-11e8-8ca4-7b958c05c35e.png)
![screen shot 2018-04-26 at 15 36 33](https://user-images.githubusercontent.com/5589858/39309195-b3c1ec8a-4967-11e8-8cfb-a76fdd22164a.png)
![screen shot 2018-04-26 at 15 36 57](https://user-images.githubusercontent.com/5589858/39309196-b3e492bc-4967-11e8-9335-6f48a1ba63c9.png)

**Comment by lucasgerard** [comment]
Our custom layout disappeared (API map erased), and the issue disappeared as well. We had to configure again our layout but collections are working.
