### ISSUE TITLE
Warnings logs on boot in serializer_factory

### ISSUE THREAD

**Issue by lucasgerard** [ForestAdmin/forest-rails#270]
## Expected behavior

Server or console should boot without warnings/errors

## Actual behavior

Starting rails server or console fire douzen of error logs such as the one below, that are not blocking though.

## Failure Logs

![screen shot 2018-07-03 at 10 36 10](https://user-images.githubusercontent.com/5589858/42208705-1ef41f9e-7ead-11e8-8f8e-c7360a4277d6.png)

## Context

* Package Version: 2.8.0
* Rails Version: 4.2.10
* Database Dialect: PG
* Database Version: 9.5

**Comment by arnaudbesnier** [comment]
Hi @lucasgerard, we don't have such issue in our test projects. I have tested with Rails 4.1.6 and Rails 5.2.0 and don't have such logs on server start.
Might be related to ruby 2.5.1 🤔

What is the warning message by the way? I might be wrong but I see the trace but not the warning itself.

**Comment by mattverlaque** [comment]
@lucasgerard - ever get this sorted? I'm having something similar, thinking it may be a bad model association somewhere in my app. Just curious, seeing similar results currently.

**Comment by AlanMcCann** [comment]
I had the same issue and it was due to a bad association. Fixing the association removed the issue.

**Comment by matthv** [comment]
Hello @lucasgerard , are you still experiencing this problem?

As indicated in the 2 previous comments, it seems that the error is not linked to our repo but to a bad model association.

**Comment by matthv** [comment]
I’m closing this inactive issue.
Don’t hesitate to open a new one if you encounter a bug.
