### ISSUE TITLE
[*] Onboarding - Cannot authenticate after project creation

### ISSUE THREAD

**Issue by jewelltl** [ForestAdmin/forest-rails#277]
Hi

I am trying to use forestadmin on my rails project.
I followed the guide, but I can not login to the forestadmin project.
Here is my steps that I tried.

https://www.useloom.com/share/418ae8af30014675980c80176084540e

I tried to change the secret_key_base and reproduced the forestadmin project, but I am getting the same issue.
It will be really thankful that you review my steps and guide me what was wrong for me.
Looking forward to hearing from you.

Thanks.

**Comment by arnaudbesnier** [comment]
Hi @leetailoong looks like we don't have the same `secret key` on our end to find your project.
One of our Customer Success guys will contact you soon to debug this. 

Thanks for your patience.
