### ISSUE TITLE
Secrets not inserted if environment is also an alias

### ISSUE THREAD

**Issue by joelcogen** [ForestAdmin/forest-rails#284]
## Expected behavior

`rails g forest_liana:install 12345` should insert into `secrets.yml` even if the environment key is also an alias:

    development: &development
      forest_env_secret: 12345
      forest_auth_secret: abcde

## Actual behavior

The generator doesn't recognize the environment and doesn't insert secrets.

    development: &development

## Context

* Package Version: 2.11.11
* Rails Version: 5.2.1

**Comment by arnaudbesnier** [comment]
Hi @joelcogen, thanks for the report.

I imagine you managed to adapt your `secrets.yml` file to make Forest work, right?

**Comment by matthv** [comment]
We are working on an evolution of this stack  and it’s planned manage this problem.

However the workaround works perfectly.

I’m closing this inactive issue.
Don’t hesitate to open a new one if you encounter a bug.
