### ISSUE TITLE
Google login impossible on new project in production - wrong liana version error

### ISSUE THREAD

**Issue by albandum** [ForestAdmin/forest-rails#293]
## Expected behavior

Being able to Google connect to a new project pushed to prod

## Actual behavior

Getting an error about not having the right forrest liana

## Failure Logs

No specific logs

## Context

I believe this is a known issue as the support has been quite responsive, they just need to 'do something' on their backed to make it work. So if you don't have a lot of projects it's a one time issue, but I will likely have a lot of new projects starting

* Package Version: 2.13.5
* Rails Version: 2.5.1
* Database Dialect: postgresql
* Database Version:

**Comment by arnaudbesnier** [comment]
Hi @albandum,

Thanks for the feedback,
can you access your production environment now?

A fix will be released next week to prevent that other users experiment the same issue after the creation of a Forest production environment.

**Comment by albandum** [comment]
Yes, but support told me to add an issue here to make sure it was known by the dev team :) 

Thanks
