### ISSUE TITLE
[*] Date Picker - Issue DateOnly fields

### ISSUE THREAD

**Issue by CFtriksX** [ForestAdmin/forest-rails#300]
## Actual behavior

When I use a date-picker to add a new date and i save it, it's modified to :
- If the hour is greater than 1H00, the date will be good but the hour will be modify to 1H00 : https://www.useloom.com/share/768559a241514c8a9dbbba660bd526b4
- If the hour is lower than 1H00, the date will be the day before at 1H00 : https://www.useloom.com/share/2d59a34b5ec74457a9b0d80abcb7b0a1

## Context

We have a time stamp for all our date, here how it's computed :
![image](https://user-images.githubusercontent.com/35850997/49385227-362f9380-f71d-11e8-91a4-8549e7cb6492.png)

and here this is what it looks like in our data base :
![image](https://user-images.githubusercontent.com/35850997/49385485-d8e81200-f71d-11e8-8dbd-872c9d676a11.png)

I've already try to modify the time-zone, it doesn't solve the problem.

* Package Version: forest_liana (2.13.0)
* Rails Version: rails (5.2.1)

**Comment by arnaudbesnier** [comment]
Hi @CFtriksX, I guess your `signature_date` field is a "DateOnly" field.
The current version of the gem does not handle well this type of column.

Can you share with us your database type and the column type in your database?

Thank you.

**Comment by arnaudbesnier** [comment]
Any news about this issue @CFtriksX ?

**Comment by arnaudbesnier** [comment]
Hi @CFtriksX , this should be fixed in the new liana version v3.1.1.

Thanks for your patience.
Feel free to reopen the thread if the issue persists after the update.
