### ISSUE TITLE
Do you only support ActiveRecord?

### ISSUE THREAD

**Issue by dmitrypol** [ForestAdmin/forest-rails#33]
I was unable to install it on Rails 5 with Mongoid 5.

**Comment by arnaudbesnier** [comment]
Hi @dmitrypol !

You're right, we only support ActiveRecord for Ruby on Rails so far.
But we could obviously support Mongoid, it's just a matter of priorities for Forest.

Don't hesitate to specify your needs, me might think about it in the future.
Thank you!
