### ISSUE TITLE
Issue with groupdate gem dependency upgrade

### ISSUE THREAD

**Issue by lostie** [ForestAdmin/forest-rails#344]
## Expected behavior

No exceptions raised.

## Actual behavior

The major version upgrade of `groupdate` gem from 4.3.0 to 5.0.0 is causing some exceptions when interacting with ForestAdmin.

## Failure Logs

<img width="1326" alt="Screenshot 2020-02-24 at 09 54 51" src="https://user-images.githubusercontent.com/67125/75149807-c0855e00-56fa-11ea-8223-071c3bcf804a.png">

## Context

* groupdate gem Version: 5.0.0
* Package Version: 4.2.0
* Rails Version: 6.0.2.1
* Database Dialect: Postgresql
* Database Version: 12.1

**Comment by arnaudbesnier** [comment]
Thanks @lostie ,
Could you detail precisely what kind of interaction or API call raise those exceptions?

**Comment by lostie** [comment]
@arnaudbesnier Sorry for having taken this long to come back to you.

The exception occurs while loading the Dashboard, here's some more info:

```ruby
Started POST "/forest/stats/Customer"
Processing by ForestLiana::StatsController#get as HTML
  Parameters: {"type"=>"■", "collection"=>"■", "timezone"=>"■", "aggregate"=>"■", "time_range"=>"■"}
ArgumentError (unknown keywords: week_start)
unknown keywords: week_start excluded from capture: DSN not set
```

<img width="1111" alt="Screenshot 2020-03-18 at 11 04 55" src="https://user-images.githubusercontent.com/67125/76954515-5ed69f00-6908-11ea-97ca-ba38d1c8ed27.png">

**Comment by arnaudbesnier** [comment]
Hi @lostie, so it might be due to a conflict between the `groupdate` gem version the liana is using (v2.5.2) et the one you use for your own codebase.

It was apparently not an issue with your `groupdate@4.3.0` gem but the v5 might introduce breaking changes that broke Forest Admin Time based charts.

**Comment by arnaudbesnier** [comment]
The patch is available in the new version 5.1.1.
Thanks for your patience.

🌲🌲🌲

**Comment by lostie** [comment]
@arnaudbesnier After upgrading to `forest_Liana` version 6.3.5, I'm experiencing issues still related with groupdate:

`ArgumentError","message":"wrong number of arguments (given 3, expected 2)`

I'lll leave the stacktrace here for reference:

```ruby
/app/vendor/bundle/ruby/3.0.0/gems/groupdate-5.2.2/lib/groupdate/query_methods.rb:13:in `group_by_period'
/app/vendor/bundle/ruby/3.0.0/gems/groupdate-5.2.2/lib/groupdate/enumerable.rb:8:in `block (3 levels) in <module:Enumerable>'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/relation.rb:406:in `block in scoping'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/relation.rb:810:in `_scoping'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.3.2/lib/active_record/relation.rb:406:in `scoping'
/app/vendor/bundle/ruby/3.0.0/gems/groupdate-5.2.2/lib/groupdate/enumerable.rb:8:in `block (2 levels) in <module:Enumerable>'
/app/vendor/bundle/ruby/3.0.0/gems/forest_liana-6.3.5/app/services/forest_liana/line_stat_getter.rb:34:in `perform'
/app/vendor/bundle/ruby/3.0.0/gems/forest_liana-6.3.5/app/controllers/forest_liana/stats_controller.rb:41:in `get'
```

**Comment by arnaudbesnier** [comment]
Hi @lostie, it might be related to this contribution:
https://github.com/ForestAdmin/forest-rails/pull/454

Can you test if the version 6.3.3 is working as expected on your project?

**Comment by jeffladiray** [comment]
Hi @lostie,

It is most likely related to #454, but I'm currently not able to reproduce.
Would it be possible to have more insights of this issue please :pray:
(Maybe a loom video or the failing chart configuration would help)

Thanks.

**Comment by lostie** [comment]
> Hi @lostie, it might be related to this contribution:
> #454
> 
> Can you test if the version 6.3.3 is working as expected on your project?

We were already on `6.3.3` before attempting to upgrading `6.3.5` and didn't experience the issue reported until we upgraded to this latest version.
