### ISSUE TITLE
[Rails 5.1.7] private method `sanitize_sql' called for ActiveRecord::Base:Class

### ISSUE THREAD

**Issue by dja** [ForestAdmin/forest-rails#378]
We're on Rails 5.1.7, and it appears this line gives us trouble since it's a private method. Flagging it here in case anyone else runs into the same issue.

https://github.com/ForestAdmin/forest-rails/blob/2662d46622e1f6d103648de36683c49147647ec3/app/services/forest_liana/filters_parser.rb#L85-L89

See: https://apidock.com/rails/v5.1.7/ActiveRecord/Sanitization/ClassMethods/sanitize_sql

**Comment by arnaudbesnier** [comment]
Hi @dja,
Thanks for the report.

Did you try to replace the condition with
`if Rails::VERSION::MAJOR >= 5 && Rails::VERSION::MINOR >= 2` ?

It would help us solve the issue quickly if it was working fine on you project with this new condition.

Thanks for your help.

**Comment by dja** [comment]
@arnaudbesnier It looks like `.sanitize` was removed for Rails 5.1, and `.sanitize_sql` was not introduced until Rails 5.2. It looks like there's no good replacement for Rails 5.1, so it may be more than just a 1-line change: https://github.com/rails/rails/issues/28947#issuecomment-440982901

**Comment by arnaudbesnier** [comment]
Thanks @dja the patch is in review.
