### ISSUE TITLE
Updating records in Rails >= 6.1 fails

### ISSUE THREAD

**Issue by lostie** [ForestAdmin/forest-rails#406]
## Expected behavior

Updating a record in the database using the ForestAdmin UI saves the record with the new values provided.

## Actual behavior

The update fails and the record is not updated in the database.

## Failure Logs

<img width="422" alt="Screenshot 2021-01-11 at 13 53 09" src="https://user-images.githubusercontent.com/67125/104190679-59f15780-5414-11eb-912c-49face1c8328.png">

## Context

[Rails 6.1 has removed](https://blog.saeloun.com/2019/04/15/rails-6-deprecates-update-attributes.html)
 `update_attributes` and `update_attributes!` in favour of `update` and `update!` respectively 

* Package Version: 5.4.0
* Rails Version: 6.1.0
* Database Dialect: Postgresql
* Database Version:

**Comment by arnaudbesnier** [comment]
Hi @lostie @berkos, the patch is available in version 5.4.3.

Thanks for you patience.
