### ISSUE TITLE
Forest stats apis return 403 Forbidden

### ISSUE THREAD

**Issue by berkos** [ForestAdmin/forest-rails#437]
## Expected behavior

Dashboard graphs on homepage of Forest should still be working after the gem upgrade to `6.1.0` from `6.0.5`.

## Actual behavior

Dashboards cannot load and getting 403 authentication errors.
Please see screenshot.

![Screenshot 2021-03-19 at 13 59 10](https://user-images.githubusercontent.com/1176797/111806651-1ca0be80-88ca-11eb-9f8d-20ed5c9e80b8.png)

## Context

TODO: Please provide any relevant information about your setup.

* Package Version: 6.1.0
* Rails Version: 6.1.3
* Database Dialect: Postgres
* Database Version: 12

Could this be related to https://github.com/ForestAdmin/forest-rails/pull/434?

**Comment by DrRaider** [comment]
Hi @berkos !
Yes it is related, we're working on a fix right now !
In the mean time, going back to `6.0.5` should get it working again.
Thanks for the heads up !

**Comment by Thenkei** [comment]
Hi @berkos,
A fix has been deployed. Let me know if everything is right on you end ?
Once again thank you for your feedback.
