### ISSUE TITLE
Conflict with groupdate gem version

### ISSUE THREAD

**Issue by khelal** [ForestAdmin/forest-rails#440]
Hi,

I'm trying to update to the latest version of the gem, but can't as there is a hard requirement for groupdate to v2.5.2, while we'on the 5.2.x version.

The version that you're using is over 4 years old (2016-02-16). Any way to update it to a more recent one so that we can upgrade?

**Comment by arnaudbesnier** [comment]
Hi @khelal,
Thanks for the feedback.

I guess it is this contribution that raises the issue:
https://github.com/ForestAdmin/forest-rails/pull/354/files

I am wondering why you can't really upgrade, as various versions of the `groupdate` gem should be able to live together. Not an expert of the Rails / Gems architecture but we implemented the fix above with this idea in mind.

Could you share the error message you get while trying to upgrade to the latest `forest_liana` gem version, to let us dig into this 🙏 
Thanks for your help.

**Comment by khelal** [comment]
This is the exact error: 
`
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.....
Bundler could not find compatible versions for gem "groupdate":
  In snapshot (Gemfile.lock):
    groupdate (= 5.2.2)

  In Gemfile:
    groupdate (~> 5.2)

    forest_liana (~> 6.3.0) was resolved to 6.3.0, which depends on
      groupdate (= 2.5.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
`

You should update your code to make sure you have accept a newer version of groupdate.

**Comment by arambert** [comment]
Hi,
I've got the same issue. It's **very** complicated in a rails app to have multiple versions of the same gem working.
IMHO it's not a good idea to keep a dependency on very old version of groupdate as it prevents other apps using up-to-date groupdate to use the forest admin gem.

**Comment by jeffladiray** [comment]
Fixed by #454, so I'm closing this.
Don't hesitate if you are still encountering an issue with this 🙏
