### ISSUE TITLE
Record count queries are extremely slow (>5 MINUTES)

### ISSUE THREAD

**Issue by dja** [ForestAdmin/forest-rails#527]
## Expected behavior

We expect counts to be super fast and optimized for performance.

## Actual behavior

Counts end up being 5+ minutes long, slowing our database to a crawl. The query should be extremely simple, like `select count(*) from invoices` instead of what you see below.

<img width="1283" alt="Screen Shot 2021-10-06 at 6 06 50 PM" src="https://user-images.githubusercontent.com/1782893/136304395-21058421-57e2-44c5-a7d3-fe27299bbcd3.png">

<img width="412" alt="Screen Shot 2021-10-06 at 6 07 11 PM" src="https://user-images.githubusercontent.com/1782893/136304426-0fc7ea66-18b5-4a9f-8ca3-05e7562a1820.png">

## Failure Logs
N/A

## Context

* Package Version: 6.3.2
* Rails Version: 5.2.5
* Database Dialect: PG
* Database Version: 10.12

**Comment by louisteenbrink** [comment]
Hi @dja 👋 ,

Forest Admin API is generating a default count query to manage the display and pagination of your data.

The solution to your problem would be to **override this default query** using [an approximative count](https://wiki.postgresql.org/wiki/Count_estimate). If you don't need an exact count, it will be much faster to retrieve the data for your big tables.

Here a code example for rails:

```
if ForestLiana::UserSpace.const_defined?('[ModelName]Controller')
  ForestLiana::UserSpace::[ModelName]Controller.class_eval do
    alias_method :default_count, :count

    # Get a number of ...
    def count
      if (!params['search'] && !params['filter'])
        sqlQuery = "SELECT reltuples AS count FROM pg_class WHERE relname = '[tableName]';"
        result = ActiveRecord::Base.connection.execute(sqlQuery)
        if result[0]
          return render serializer: nil, json: { count: result[0]['count'] }
        end
        default_count
      else
        default_count
      end
    end
  end
end
```

Let me know if that helps!

**Comment by matthv** [comment]
The solution was given in @louisteenbrink's previous comment.

I’m closing this inactive issue.
Don’t hesitate to open a new one if you encounter a bug.
