### ISSUE TITLE
Lifecycle question

### ISSUE THREAD

**Issue by statushub-piotr** [ForestAdmin/forest-rails#531]
Hi,
Is there any exact lifecycle policy where I could check when certain major versions will be deprecated and when blocked ?
For example currently on V4 there is an info that this version will be blocked. But I would like to know if it will be blocked this month, this year or maybe late 2022 ?

**Comment by arnaudbesnier** [comment]
Hi @statushub-piotr,

We have no agent support policy so far.
This is something we will work on in 2022.

So we still support very old agent versions (and we will continue to do so unless we communicate clearly), but we try to encourage users to upgrade for more features, more security, better maintenance and support. That’s why you probably have a deprecation warning when you start your server.

v4 is more than 2 years and half old, I encourage you to upgrade to the latest major (v7) following the upgrade notes ([v5](https://docs.forestadmin.com/documentation/how-tos/maintain/upgrade-notes-rails/untitled), [v6](https://docs.forestadmin.com/documentation/how-tos/maintain/upgrade-notes-rails/upgrade-to-v6), [v7](https://docs.forestadmin.com/documentation/how-tos/maintain/upgrade-notes-rails/upgrade-to-v7))

Hope it helps.

**Comment by statushub-piotr** [comment]
Yes, we will definitely do the update but I wanted to know about any potential deadlines to help schedule the work. Thanks!
