### ISSUE TITLE
Associations with restrict_with_error not handled properly

### ISSUE THREAD

**Issue by jordanell** [ForestAdmin/forest-rails#630]
## Expected behavior

If I have a model with an association defined like so:

# post.rb
```ruby
has_many :comments, dependent: :restrict_with_error
```

I would expect that if a `post` has 1 or more `comments` and is deleted inside of Forest, it should result in an error being displayed.

## Actual behavior

When I delete the `post` right now, the post isn't actually deleted (correctly), but the Forest controller responds with 204 and a successful flash message is shown on the screen even though the post is not deleted.

* Package Version: 7.8.0
* Rails Version: 7.0.7.1
* Database Dialect: PostgreSQL
* Database Version: 14.9

**Comment by matthv** [comment]
Hello @jordanell 

I managed to reproduce the issue on my end.
I'm opening a ticket on our side and I'll get back to you as soon as the patch is ready.

Sorry for the inconvenience

**Comment by matthv** [comment]
I just added a fix on a branch to avoid this problem.

Could you try with this branch?
Just edit your Gemfile like this:

`gem 'forest_liana', git: 'https://github.com/ForestAdmin/forest-rails.git', branch: 'fix/destroy-record-with-restriction-on-children'`

then run

`bundle install`

Tell me if it works on your side :pray:
