### ISSUE TITLE
Question about polymorphic associations support

### ISSUE THREAD

**Issue by lostie** [ForestAdmin/forest-rails#642]
## Expected behavior

When using the new version of the gem that supports polymorphic associations, following the instructions in the README file (which does not contain any specific instructions to enable polymorphic associations), I was expecting to be able to see a link to the polymorphic association and be able to navigate to the record page

## Actual behavior

* With **no additional configuration**, I'm seeing the old behaviour, where the polymorphic association fields (`<record>_type` and `<record>_id`) are shown as text fields.
* I was able to enable the support for polymorphic associations **setting the environment variable** `ENABLE_SUPPORT_POLYMORPHISM` to `true` and after that I can see a link to the polymorphic association and I'm able to navigate to the record page, but I'm not entirely sure if (and why) I'm expected to use this environment variable to enable this behaviour or if the support for polymorphic associations is expected to be enabled by default.

## Failure Logs

N/A

## Context

* Package Version: 8.1.0
* Rails Version: 7.1.3
* Database Dialect: Postgresql
* Database Version: 16

**Comment by nicolasalexandre9** [comment]
Hi, 

Documentation is currently being written.
As you said, for enabled the feature you need to add the environment varaible `ENABLE_SUPPORT_POLYMORPHISM` to `true`. 
By default polymorphic associations support is disabled because, when this feature is activated the `<record>_type` and `<record>_id` fields are no longer returned by the API.

**Comment by nicolasalexandre9** [comment]
Hi, 

After some discussions with the technical team, we've decided to release a v9 of forest-rails that enables polymorphic support by default. As a result, from V9 onwards, the env variable "ENABLE_SUPPORT_POLYMORPHISM" is no longer required.  A note on upgrading from V8 to V9 is available [here](https://docs.forestadmin.com/documentation/extra-help/maintain/upgrade-notes-rails/upgrade-to-v9).
