### ISSUE TITLE
Usage of rails secrets raises deprecation warnings on Rails 7.1+

### ISSUE THREAD

**Issue by dvkch** [ForestAdmin/forest-rails#648]
Hi there,

I am currently in the process of migrating a Rails app to Rails 7.1, and I found that Forest's usage of `Rails.application.secrets` usage in `boostrapper.rb` raises a deprecation warning/exception (depending on your configuration).

This check seems to have been there for 2 years now, would it be possible to remove it ? Or at least check only if `ForestLiana.application_url` hasn't already been set before.

For reference, here is the offending line: <https://github.com/ForestAdmin/forest-rails/blob/8cbdea38c7d38d7f31a0f4d3b54f926d506421e0/lib/forest_liana/bootstrapper.rb#L31>

Thank you for considering :)

**Comment by matthv** [comment]
Hi @dvkch , thanks for your feedback

I have just created a ticket on our end to remove this warning.
I will let you know when it's processed.

**Comment by dvkch** [comment]
Thank you !

**Comment by matthv** [comment]
hello @dvkch, I have just released version `9.3.10` which removes the deprecated warning.

**Comment by dvkch** [comment]
Great, thanks for the update!
