### ISSUE TITLE
Unable to create record with polymorphic field

### ISSUE THREAD

**Issue by cyruxwong** [ForestAdmin/forest-rails#668]
## Expected behavior

When creating record via FA UI, I should able to create the record with polymorphic field defined.

## Actual behavior

I was not able to create a new record.
I received an error message from UI after clicking the "Create" button:
`Record creation failed: Resource must exist`, where "Resource" is the polymorphic field in my model.

## Failure Logs

N/A

## Context

Strangely, I can update existing records with polymorphic field defined. 🤔 

And I realised the problem should happen in the UI side.
I am using "Polymorphic BelongsTo Typeahead" control in the UI:
<img width="665" alt="image" src="https://github.com/ForestAdmin/forest-rails/assets/50318899/8b3bd146-12b6-43fa-ba18-0ec2b7ba4b3a">
For example, I have selected "Variant" as the type and lookup an item. But the type has been changed to "VariantCluster" unexpectedly in the creation HTTP request payload:
<img width="629" alt="image" src="https://github.com/ForestAdmin/forest-rails/assets/50318899/b4ad53df-dc3c-48d4-bf05-43e8df77af05">
PS: VariantCluster is one of the possible types of this polymorphic field.

By selecting different types from the control, I can confirm:
The creation will be failed if I have selected a type that there is another type with a similar name (e.g. Product vs ProductCategory) in the list.

* Package Version: 9.3.0
* Rails Version: 7.1.3.2
* Database Dialect: Postgresql
* Database Version: v15

Please help. Thanks.

**Comment by ShohanRahman** [comment]
Hi @cyruxwong ,

Sorry for the late answer. We did reproduce the issue and will tacke this subject as soon as possible.
I will keep you updated when it will be fixed.

Our apologies for the inconveniences.

Best regards,

Shohan

**Comment by nicolasalexandre9** [comment]
Hi @cyruxwong,

We’ve just released a new version of the forest_liana(V9.3.4) that fix this issue.
