### ISSUE TITLE
New polymorphic update breaks exporting id and type now just blank

### ISSUE THREAD

**Issue by rchasman** [ForestAdmin/forest-rails#669]
## Expected behavior

When exporting from Forest Admin, records including the `listable` polymorphic field have `listable_id` and `listable_type` columns as before.

Our support team used this to concatenate the type and id into a url for delivering data to customers. I tried to make a Smart Field to alleviate this. It shows up in Forest, but is also blank in the export.

## Actual behavior

Now export from forest has `listable` column with nothing filled in.

## Failure Logs

![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/2d16919d-b487-4190-92ae-3c5795a23440)

## Context

Rails 6
forest_liana (9.2.0)

**Comment by nicolasalexandre9** [comment]
Hi @rchasman, 

Since version v9, the `<record>_type` and `<record>_id` fields are no longer returned by the API. You can see [here](https://docs.forestadmin.com/documentation/extra-help/maintain/upgrade-notes-rails/upgrade-to-v9#breaking-changes) the breaking change note.

You can create a smartfield to add these fields back to the list. 
Here's an example below: 

```
field :listable_type, type: 'String' do
  object.listable_type
end

field :listable_id, type: 'String' do
  object.listable_id
end
```

**Comment by rchasman** [comment]
That would be a fine work around. However it seems that smart fields (even string ones) export as blank as well. Sorry I know this may be outside of the realm of this codebase at this point.

**Comment by nicolasalexandre9** [comment]
Are your smart fields also empty on the list or only on the export ?

**Comment by rchasman** [comment]
![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/b7ab8640-db67-493d-8385-8bf01cbbf288)

They are not empty on the list. Just on the export.

**Comment by rchasman** [comment]
Sure I filtered it down a bit but the headers are there, yet the response is blank for the column.

![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/4ff37a07-2ccd-4125-8584-3f8d9e0a7646)
![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/2e142d89-aef6-4740-b938-9fd2a42e4548)

It shows up in Forest ui. Not in the export.

I also tried your recommendation and there was no change!

**Comment by nicolasalexandre9** [comment]
Could you try to put debugger in your smart field block and check if the object variable contain the listable_type and listable_id attributes ?

**Comment by rchasman** [comment]
I did that and yeah they do. That's why this smart field shows up in Forest Admin correctly! It just doesn't seem to export smart fields for some reason 🤔

**Comment by nicolasalexandre9** [comment]
Do you have override the list/export route ? 
Can you also share the list call headers to compare them with the export call headers ?

**Comment by rchasman** [comment]
No I don't override the list/export route. Would that be a path towards fixing this?

In UI list request (working):

```
https://lm.lawmatics.com/forest/Firm/2907/relationships/automation_lists?timezone=America%2FLos_Angeles&fields%5BAutomationList%5D=automation%2Cfirm%2Cstatus%2Ccreated_at%2Cupdated_at%2Ctype%2Cid%2Clistable%2Clistable_url%2Cworker_dispatched%2Cdeleted_at%2Csearch_synced_at&fields%5Bautomation%5D=name&fields%5Bfirm%5D=name&page%5Bnumber%5D=1&page%5Bsize%5D=10&sort=-id
```

![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/bdcce447-71c5-4bf0-952e-701dfa2967a4)

Export list request:
```
https://lm.lawmatics.com/forest/Firm/2907/relationships/automation_lists.csv?fields%5BAutomationList%5D=automation%2Cfirm%2Cstatus%2Ccreated_at%2Cupdated_at%2Ctype%2Cid%2Clistable%2Clistable_url%2Cworker_dispatched%2Cdeleted_at%2Csearch_synced_at&fields%5Bautomation%5D=name&fields%5Bfirm%5D=name&page%5Bnumber%5D=1&page%5Bsize%5D=10&sort=-id&filename=automation+targets&header=automation%2Cfirm%2Cstatus%2Ccreated+at%2Cupdated+at%2Ctype%2Cid%2Clistable%2Clistable+url%2Cworker+dispatched%2Cdeleted+at%2Csearch+synced+at&sessionToken=&timezone=America%2FLos_Angeles
```
Same records. It's blank
![image](https://github.com/ForestAdmin/forest-rails/assets/1267219/9b946aa8-cc1c-44d1-b788-2396523224a4)

**Comment by rchasman** [comment]
Closing as you are supporting via email thanks!
