### ISSUE TITLE
Can't have custom class names for associations

### ISSUE THREAD

**Issue by dpalumbo** [ForestAdmin/forest-rails#78]
For example, I have a table called transactions. I had to make a custom association name because `.transaction` is reserved:

```
  belongs_to :a_transaction, :class_name => "Transaction"
```

This causes a bug though when trying to load the data:

```
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column communications.a_transaction_id does not exist
```

Is it possible to support custom association names?

**Comment by SeyZ** [comment]
Hey @dpalumbo 

Can you share the revelant part of the `schema.rb` file: table `communications` --> field `a_transaction` ?

**Comment by dpalumbo** [comment]
```
  create_table "communications", force: :cascade do |t|
    t.integer  "transaction_id"
  end
```

**Comment by SeyZ** [comment]
@dpalumbo I think you have to add the `foreign_key` attribute in your field declaration:

  belongs_to :a_transaction, :class_name => "Transaction", :foreign_key => "transaction_id"

Otherwise, Rails uses `a_transaction_id`. Am I wrong?

**Comment by dpalumbo** [comment]
Nope you are right. I will close this.
