### ISSUE TITLE
unitializedconstant Forestliana error

### ISSUE THREAD

**Issue by manueld12** [ForestAdmin/forest-rails#88]
ruby version 2.2.0
activerecord 4.2.1
rails 4.2.1

More information about the error from terminal here 
https://gist.github.com/gsapophis/6474aee0641986a3b5cdefddf8f93a67

**Comment by arnaudbesnier** [comment]
@manueld12, can you provide more details about your issue?
For example, what steps did you follow to install Forest on your Rails app?
Did it work in a previous gem version?

By the way, it seem that you are using version 1.4.1.
You should update the gem to the latest version (1.4.7).

**Comment by manueld12** [comment]
Ok . Yes that fixed it. Thank you
